# Generated by Django 2.0.7 on 2018-08-09 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=False)),
                ('data_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField()),
                ('data_commentary', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('data_commentary',),
            },
        ),
        migrations.CreateModel(
            name='CommentaryReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('data_reply', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clienteSide.Commentary', verbose_name='Referente a este comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Quem respondeu ao comentario')),
            ],
            options={
                'ordering': ('data_reply',),
            },
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('state', models.BooleanField(default=False)),
                ('data_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='Obra não possui descrição.', null=True)),
                ('url', models.FileField(upload_to=None)),
                ('data_registered', models.DateField(auto_now_add=True)),
                ('data_creation', models.DateField(auto_now_add=True)),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clienteSide.Licenca', verbose_name='Disponivel sob a licença:')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ObraAdquirida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisition', models.DateField(auto_now_add=True)),
                ('signature', models.TextField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clienteSide.Obra', verbose_name='Obra adquirida sob licença')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Quem adquiriu a obra.')),
            ],
            options={
                'ordering': ('data_aquisition',),
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user/profile-image/')),
                ('state', models.BooleanField(default=False)),
                ('data_creation', models.DateField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area', to='clienteSide.AreaAplicacao')),
            ],
            options={
                'ordering': ('data_creation',),
            },
        ),
        migrations.CreateModel(
            name='TipoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('state', models.BooleanField(default=False)),
                ('data_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TipoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.BooleanField(default=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clienteSide.TipoPerfil', verbose_name='Tipo de perfil do associado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obra',
            name='type_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clienteSide.TipoObra', verbose_name='Tipo de obra'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clienteSide.Obra', verbose_name='Comentario referente a obra:'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Quem comentou a obra:'),
        ),
    ]
